Fix client-default-dscp setting being neither client- nor server-side
Summary:
kolmike@devvm3887:~$ ldshell deploy -t logdevice.scribe.ldtest.lla1-1 -y --atonce=1000 --package=logdevice.server_experimental_dbgo:0398c5b
  Logging to /tmp/ldshell-otte9lbk
  Logging Level: WARNING
  Deploying 192 hosts...
  Error running command: Invalid settings in config: 'client-default-dscp' cannot be set in this context because it does not match the predetermined flag
  ------------------------------------------------------------
  Traceback (most recent call last):
    File "logdevice/ldops/config/config.py", line 522, in validate
  ValueError: 'client-default-dscp' cannot be set in this context because it does not match the predetermined flag

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "nubia/internal/cmdbase.py", line 468, in run_cli
    File "ldshell/fb/commands/daemon.py", line 981, in run
    File "ldshell/fb/commands/daemon.py", line 199, in run
    File "ldshell/fb/commands/daemon.py", line 1018, in batch_runner
    File "logdevice/ldops/internal/tier.py", line 1522, in clear_hosts_property
    File "logdevice/ldops/config/config.py", line 316, in save
    File "logdevice/ldops/config/config.py", line 551, in validate
  logdevice.ldops.config.exceptions.InvalidConfigError: Invalid settings in config: 'client-default-dscp' cannot be set in this context because it does not match the predetermined flag
  ------------------------------------------------------------

Reviewed By: Zepheus

Differential Revision: D14492317

fbshipit-source-id: 73e3dbcc48717ef86995a8bc64ba9add57dd26f5