Fix open source build by linking against libthriftmetadata.so (#176)
Summary:
Pull Request resolved: https://github.com/facebookincubator/LogDevice/pull/176

Fix OSS build error:

```
/usr/bin/ld: ../../lib/libadmin-cpp2.a(admin_metadata.cpp.o): undefined reference to symbol '_ZNKR6apache6thrift8metadata20ThriftServiceContext16get_service_infoEv'
//root/project/_build/fbthrift-prefix/src/fbthrift-build/lib/libthriftmetadata.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Differential Revision: D20257545

fbshipit-source-id: 92e776ca2a3b24c64b88f349b4d189996d5bac41